NAME = "PlayStation® 3"
MANUFACTURER = "Sony"
DOMAIN = "ps3"
PLATFORMS = ["climate", "number", "media_player"]
DATA_HASS_CONFIG = "ps3_hass_config"
CONF_ENTRY_ID = "entry_id"
ENTRIES = "entries"
MAX_TEMP = 85
MIN_TEMP = 40
MAX_FAN_SPEED = 100
MIN_FAN_SPEED = 3
FAN_SPEED_INCREASE = 1.0
XMB_SOURCE = 'XMB/Physical Disc'
TURN_ON_SCRIPT = 'turn_on_script'
SCRIPT_DOMAIN = 'script'
FAN_SPEED_KEY = 'fan_speed'
MEDIA_PLAYER_KEY = 'media_player'
SYSTEM_TEMP_KEY = 'system_temp'